/**
 * Template Engine Usage Examples
 *
 * Demonstrates how to use the Template Engine for code generation
 */

import { TemplateEngine } from '../src/core/template-engine.js';

// Example 1: Simple TypeScript Interface Generation
function generateTypeScriptInterface() {
  const engine = new TemplateEngine();

  const template = `
{{blockComment description}}
export interface {{PascalCase name}} {
{{#each properties}}
  {{#if description}}{{comment description "//"}}{{/if}}
  {{camelCase name}}{{#unless required}}?{{/unless}}: {{type}};
{{/each}}
}
`;

  const context = {
    name: 'user_profile',
    description: 'User profile data structure',
    properties: [
      {
        name: 'user_id',
        type: 'string',
        required: true,
        description: 'Unique user identifier',
      },
      { name: 'email_address', type: 'string', required: true },
      { name: 'display_name', type: 'string', required: false },
      { name: 'age', type: 'number', required: false },
    ],
  };

  const result = engine.render(template, context);
  console.log('TypeScript Interface:\n', result.output);
  return result.output;
}

// Example 2: Python Class Generation
function generatePythonClass() {
  const engine = new TemplateEngine();

  const template = `
{{blockComment description "\"\"\"" "\"\"\""}}
class {{PascalCase name}}:
    def __init__(self{{#each fields}}, {{snake_case name}}: {{type}}{{/each}}):
{{#each fields}}
        self.{{snake_case name}} = {{snake_case name}}
{{/each}}

{{#each methods}}
    def {{snake_case name}}(self{{#each params}}, {{snake_case name}}: {{type}}{{/each}}) -> {{returnType}}:
        {{blockComment description "\"\"\"" "\"\"\""}}
        {{#if (eq returnType "None")}}pass{{else}}return None{{/if}}
{{/each}}
`;

  const context = {
    name: 'api_client',
    description: 'API client for making HTTP requests',
    fields: [
      { name: 'apiKey', type: 'str' },
      { name: 'baseUrl', type: 'str' },
      { name: 'timeout', type: 'int' },
    ],
    methods: [
      {
        name: 'getUser',
        description: 'Get user by ID',
        params: [{ name: 'userId', type: 'str' }],
        returnType: 'User',
      },
      {
        name: 'createUser',
        description: 'Create a new user',
        params: [{ name: 'userData', type: 'dict' }],
        returnType: 'User',
      },
    ],
  };

  const result = engine.render(template, context);
  console.log('\nPython Class:\n', result.output);
  return result.output;
}

// Example 3: Rust Struct with Custom Helpers
function generateRustStruct() {
  const engine = new TemplateEngine();

  // Register custom helper for Rust type mapping
  engine.registerHelper('rustType', (type: string) => {
    const typeMap: Record<string, string> = {
      string: 'String',
      number: 'f64',
      integer: 'i64',
      boolean: 'bool',
      array: 'Vec',
      object: 'HashMap',
    };
    return typeMap[type.toLowerCase()] || 'String';
  });

  const template = `
{{#if description}}{{blockComment description "///" "///"}}{{/if}}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct {{PascalCase name}} {
{{#each fields}}
    {{#if description}}{{comment description "///"}}{{/if}}
    {{#if (not required)}}#[serde(skip_serializing_if = "Option::is_none")]{{/if}}
    pub {{snake_case name}}: {{#if required}}{{rustType type}}{{else}}Option<{{rustType type}}>{{/if}},
{{/each}}
}

impl {{PascalCase name}} {
    pub fn new({{#each (filter fields "required")}}{{snake_case name}}: {{rustType type}}{{#unless @last}}, {{/unless}}{{/each}}) -> Self {
        Self {
{{#each fields}}
            {{snake_case name}}: {{#if required}}{{snake_case name}}{{else}}None{{/if}},
{{/each}}
        }
    }
}
`;

  // Register filter helper for filtering required fields
  engine.registerHelper('filter', (array: any[], property: string) => {
    return array.filter((item) => item[property]);
  });

  const context = {
    name: 'UserData',
    description: 'User data structure with optional fields',
    fields: [
      { name: 'userId', type: 'string', required: true },
      { name: 'email', type: 'string', required: true },
      {
        name: 'phoneNumber',
        type: 'string',
        required: false,
        description: 'Optional phone number',
      },
      { name: 'age', type: 'integer', required: false },
    ],
  };

  const result = engine.render(template, context);
  console.log('\nRust Struct:\n', result.output);
  return result.output;
}

// Example 4: Using Partials
function generateWithPartials() {
  const engine = new TemplateEngine();

  // Register partials
  engine.registerPartial(
    'fileHeader',
    `{{comment "Auto-generated by LLM-Forge. Do not edit manually." "//"}}
{{comment (concat "Generated at: " timestamp) "//"}}`
  );

  engine.registerPartial(
    'property',
    `  {{camelCase name}}{{#unless required}}?{{/unless}}: {{type}};`
  );

  const template = `
{{> fileHeader}}

export interface {{PascalCase name}} {
{{#each properties}}
{{> property}}
{{/each}}
}
`;

  const context = {
    name: 'api_response',
    timestamp: new Date().toISOString(),
    properties: [
      { name: 'status_code', type: 'number', required: true },
      { name: 'message', type: 'string', required: true },
      { name: 'data', type: 'any', required: false },
    ],
  };

  const result = engine.render(template, context);
  console.log('\nWith Partials:\n', result.output);
  return result.output;
}

// Example 5: Complex Template with Switch/Case
function generateWithSwitchCase() {
  const engine = new TemplateEngine();

  const template = `
export type ValidationRule = {{#each rules}}
  | { type: '{{type}}'; {{#switch type}}
    {{#case "minLength" "maxLength"}}value: number;{{/case}}
    {{#case "pattern"}}regex: RegExp;{{/case}}
    {{#case "custom"}}validator: (value: any) => boolean;{{/case}}
    {{#default}}options: Record<string, unknown>;{{/default}}
  {{/switch}} }
  {{#unless @last}}{{/unless}}{{/each}};

export function validate(value: any, rule: ValidationRule): boolean {
  switch (rule.type) {
{{#each rules}}
    case '{{type}}':
      {{#switch type}}
        {{#case "minLength"}}return value.length >= rule.value;{{/case}}
        {{#case "maxLength"}}return value.length <= rule.value;{{/case}}
        {{#case "pattern"}}return rule.regex.test(value);{{/case}}
        {{#case "custom"}}return rule.validator(value);{{/case}}
        {{#default}}return true;{{/default}}
      {{/switch}}
{{/each}}
    default:
      return false;
  }
}
`;

  const context = {
    rules: [
      { type: 'minLength' },
      { type: 'maxLength' },
      { type: 'pattern' },
      { type: 'custom' },
      { type: 'required' },
    ],
  };

  const result = engine.render(template, context);
  console.log('\nSwitch/Case Example:\n', result.output);
  return result.output;
}

// Example 6: Using Math Helpers
function generateWithMath() {
  const engine = new TemplateEngine();

  const template = `
// Grid system with {{columns}} columns
export const gridConfig = {
  columns: {{columns}},
  gutterSize: {{gutterSize}},

  // Calculated values
  columnWidth: {{divide (subtract 100 (multiply gutterSize (subtract columns 1))) columns}}%,
  maxContainerWidth: {{multiply columns columnWidth}}px,

  // Responsive breakpoints
  breakpoints: {
{{#each breakpoints}}
    {{camelCase name}}: {{value}}px, // ~{{round (divide value 16)}}rem
{{/each}}
  },

  // Z-index layers
  zIndex: {
{{#each (range 1 6)}}
    layer{{this}}: {{multiply this 100}},
{{/each}}
  }
};
`;

  // Register range helper
  engine.registerHelper('range', (start: number, end: number) => {
    return Array.from({ length: end - start }, (_, i) => start + i);
  });

  const context = {
    columns: 12,
    gutterSize: 16,
    columnWidth: 80,
    breakpoints: [
      { name: 'mobile', value: 320 },
      { name: 'tablet', value: 768 },
      { name: 'desktop', value: 1024 },
      { name: 'wide', value: 1440 },
    ],
  };

  const result = engine.render(template, context);
  console.log('\nMath Helpers Example:\n', result.output);
  return result.output;
}

// Run all examples
function runAllExamples() {
  console.log('===== Template Engine Examples =====\n');

  generateTypeScriptInterface();
  generatePythonClass();
  generateRustStruct();
  generateWithPartials();
  generateWithSwitchCase();
  generateWithMath();

  console.log('\n===== All Examples Complete =====');
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  runAllExamples();
}

export {
  generateTypeScriptInterface,
  generatePythonClass,
  generateRustStruct,
  generateWithPartials,
  generateWithSwitchCase,
  generateWithMath,
  runAllExamples,
};
